<?php
return [
  'settings' => [
    'site_name' => 'G2EX',
    'slogan' => 'Это сообщество единомышленников.',
    'description' => 'Сообщество по интересам и увлекательному общению',
    'icp' => '',
    'admin_email' => 'admin@site.ru',
    'offline' => '0',
    'offline_msg' => 'Приносим свои извинения, но сайт временно закрыт на технические работы',
    'access_auth' => '0',
    'email_verify' => '0',
    'admin_verify' => '0',
    'close_register' => '0',
    'username_filter' => 'admin,webmaster,admin*',
    'captcha_enabled' => '0',
    'autolink' => '1',
    'autolink_filter' => [
    ],
    'theme' => 'g2ex',
    'theme_mobile' => 'mobile',
    'groups' => [
      [
        '1500',
        'USER',
      ],
      [
        '3000',
        'BRONZE',
      ],
      [
        '5000',
        'SILVER',
      ],
      [
        '8000',
        'GOLD',
      ],
      [
        '15000',
        'PLATINUM',
      ],
      [
        '100000000',
        'AD',
      ],
    ],
    'head_meta' => '',
    'analytics_code' => '',
    'footer_links' => [
    ],
    'timezone' => 'Europe/Moscow',
    'editor' => 'WysibbEditor',
    'cache_enabled' => '0',
    'cache_time' => '10',
    'auth_enabled' => '1',
    'auth_setting' => [
    ],
    'index_pagesize' => '20',
    'list_pagesize' => '20',
    'comment_pagesize' => '20',
    'hot_topic_num' => '5',
    'hot_node_num' => '20',
    'edit_space' => '30',
    'topic_space' => '30',
    'comment_space' => '20',
    'alias_static' => '',
    'alias_avatar' => '',
    'alias_upload' => '',
    'mailer_host' => 'smtp.163.com',
    'mailer_port' => '25',
    'mailer_encryption' => '',
    'mailer_username' => '',
    'mailer_password' => '',
    'upload_avatar' => 'local',
    'upload_file' => 'local',
    'upload_file_regday' => '0',
    'upload_file_topicnum' => '0',
    'upload_remote' => '',
  ]
];
